//begin player constants
export const CHANGE_PLAYER_STATUS = 'CHANGE_PLAYER_STATUS'
export const CHANGE_AUDIO_SRC = 'CHANGE_AUDIO_SRC'
export const PLAYER_PLAYING = 'PLAYER_PLAYING';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_LOADED = 'PLAYER_LOADED';
export const PLAYER_BUFFERING = 'PLAYER_BUFFERING';
export const ADD_SONG_TO_QUEUE = 'ADD_SONG_TO_QUEUE';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';
export const REMOVE_ITEM_FROM_QUEUE = 'REMOVE_ITEM_FROM_QUEUE';
//end player constants
//begin authentication reducers
export const API_BASE_URL = 'https://localhost:8443';
export const ACCESS_TOKEN = 'accessToken';
export const OAUTH2_REDIRECT_URI = 'https://localhost:3000/oauth2-redirect'
export const GOOGLE_AUTH_URL = API_BASE_URL + '/oauth2/authorize/google?redirect_uri=' + OAUTH2_REDIRECT_URI;
export const FACEBOOK_AUTH_URL = API_BASE_URL + '/oauth2/authorize/facebook?redirect_uri=' + OAUTH2_REDIRECT_URI;
export const GITHUB_AUTH_URL = API_BASE_URL + '/oauth2/authorize/github?redirect_uri=' + OAUTH2_REDIRECT_URI;
 export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
 export const LOGIN_FAILED = "LOGIN_FAILED";
 export const LOGINING = "LOGINING";
 export const LOADING_CURRENT_USER= "LOADING_CURRENT_USER";
 export const LOADING_CURRENT_USER_SUCCESS = "LOADING_CURRENT_USER_SUCCESS";
 export const LOADING_CURRENT_USER_FAIL = "LOADING_CURRENT_USER_FAIL";
 export const LOG_OUT = "LOG_OUT";

export const SIGNING_UP = "SIGNING_UP";
export const SIGN_UP_SUCCESS= "SIGIN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

//Song constants
export const GETTING_ALL_SONG_PAGING = 'GETTING_ALL_SONG_PAGING';
export const GET_ALL_SONG_PAGING_SUCCESS = 'GET_ALL_SONG_PAGING_SUCCESS';
export const GET_ALL_SONG_PAGING_FAIL = 'GET_ALL_SONG_PAGING_FAIL';
export const GETTING_SONG_BY_SINGER_PAGING = 'GETTING_SONG_BY_SINGER_PAGING';
export const GET_SONG_BY_SINGER_PAGING_SUCCESS = 'GET_SONG_BY_SINGER_PAGING_SUCCESS';
export const GET_SONG_BY_SINGER_PAGING_FAIL = 'GET_SONG_BY_SINGER_PAGING_FAIL';
export const GETTING_TOP_5_LIKE = 'GETTING_TOP_5_LIKE';
export const GET_TOP_5_LIKE_SUCCESS = 'GET_TOP_5_LIKE_SUCCESS';
export const GET_TOP_5_LIKE_FAIL = 'GET_TOP_5_LIKE_FAIL';
export const GETTING_TRENDING_SONGS = 'GETTING_TRENDING_SONGS';
export const GET_TRENDING_SONGS_SUCCCESS = 'GET_TRENDING_SONGS_SUCCCESS';
export const GET_TRENDING_SONGS_FAIL = 'GET_TRENDING_SONGS_FAIL';
export const WIPE_FETCH_ON_SCROLL_SONGS = "WIPE_FETCH_ON_SCROLL_SONGS";
export const GETTING_RANDOM_4_JAZZ = 'GETTING_RANDOM_4_JAZZ'; 
export const GET_RANDOM_4_JAZZ_SUCCESS = 'GET_RANDOM_4_JAZZ_SUCCESS'; 
export const GET_RANDOM_4_JAZZ_FAIL = 'GET_RANDOM_4_JAZZ_FAIL'; 
export const GETTING_8_NEWEST = 'GETTING_8_NEWEST'; 
export const GET_8_NEWEST_SUCCESS = 'GET_8_NEWEST_SUCCESS'; 
export const GET_8_NEWEST_FAIL = 'GET_8_NEWEST_FAIL'; 
export const GETTING_RANDOM_4_POP = 'GETTING_RANDOM_4_POP'; 
export const GET_RANDOM_4_POP_SUCCESS = 'GET_RANDOM_4_POP_SUCCESS'; 
export const GET_RANDOM_4_POP_FAIL = 'GET_RANDOM_4_POP_FAIL'; 
export const GETTING_DISCOVER_HEADER_DATA = 'GETTING_DISCOVER_HEADER_DATA';
export const GET_DISCOVER_HEADER_DATA_SUCCESS = 'GET_DISCOVER_HEADER_DATA_SUCCESS';
export const GET_DISCOVER_HEADER_DATA_FAIL = 'GET_DISCOVER_HEADER_DATA_FAIL';
export const GETTING_TOP_POPULAR_BY_SINGER = 'GETTING_TOP_POPULAR_BY_SINGER';
export const GET_TOP_POPULAR_BY_SINGER_SUCCESS = 'GET_TOP_POPULAR_BY_SINGER_SUCCESS';
export const GET_TOP_POPULAR_BY_SINGER_FAIL = 'GET_TOP_POPULAR_BY_SINGER_FAIL';
export const GETTING_SONG_BY_ID = 'GETTING_SONG_BY_ID';
export const GET_SONG_BY_ID_SUCCESS = 'GET_SONG_BY_ID_SUCCESS';
export const GET_SONG_BY_ID_FAIL = 'GET_SONG_BY_ID_FAIL';
export const GETTING_SONG_BY_USER_ID = 'GETTING_SONG_BY_USER_ID';
export const GET_SONG_BY_USER_ID_SUCCESS = 'GET_SONG_BY_USER_ID_SUCCESS';
export const GET_SONG_BY_USER_ID_FAIL = 'GET_SONG_BY_USER_ID_FAIL';
export const LIKING_SONG = 'LIKING_SONG';
export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS';
export const LIKE_SONG_FAIL = 'LIKE_SONG_FAIL';
//Song constants

//singer const
export const GETTING_ALL_SINGERS_PAGING = 'GETTING_ALL_SINGERS_PAGING';
export const GET_ALL_SINGERS_PAGING_SUCCESS = 'GET_ALL_SINGERS_PAGING_SUCCESS';
export const GET_ALL_SINGERS_PAGING_FAIL = 'GET_ALL_SINGERS_PAGING_FAIL';
export const WIPE_FETCH_ON_SCROLL_SINGERS = "WIPE_FETCH_ON_SCROLL_SINGERS";
export const GETTING_SINGER_BY_ID = 'GETTING_SINGER_BY_ID';
export const GET_SINGER_BY_ID_SUCCESS = 'GET_SINGER_BY_ID_SUCCESS';
export const GET_SINGER_BY_ID_FAIL = 'GET_SINGER_BY_ID_FAIL';
//singer const

//search const
export const SEARCHING_SONGS_AND_SINGERS = 'SEARCHING_SONGS_AND_SINGERS';
export const SEARCH_SONGS_AND_SINGERS_SUCCESS = 'SEARCH_SONGS_AND_SINGERS_SUCCESS';
export const SEARCH_SONGS_AND_SINGERS_FAIL = 'SEARCH_SONGS_AND_SINGERS_FAIL';
//search const